services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_clean_arch
    command: postgres -c 'max_connections=5000'
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username",
          "user",
          "--dbname",
          "go_clean_arch",
        ]
      interval: 5s
      timeout: 10s
      retries: 5