name: continuos integrations
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: build
        run: go build -v ./...
      - name: lint
        run: golangci/golangci-lint-action@v4
        with:
          version: 1.51