name: continuos integrations
on:
  push:
    branches:
      - main
      - development
      - feature/*
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: build
        run: go build -v ./...
      - name: lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
      - name: test
        run: go test -v ./... -cover