name: CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
      - feature/*
  release:
    types: [published]
jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: build
        run: go build -v ./...
      - name: lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
      - name: test
        run: go test -v ./... -cover
  # continuos-deployment:
  #   needs: continuos-integration
  #   runs-on: ubuntu-latest
  #   if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1 
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: false
  #         tags: wesleywillians/fc2.0-ci-go:latest
